catalog:
  '@eslint/js': ^9.32.0
  '@livestore/adapter-web': ^0.3.1
  '@livestore/devtools-vite': ^0.3.1
  '@livestore/livestore': ^0.3.1
  '@livestore/peer-deps': ^0.3.1
  '@livestore/react': ^0.3.1
  '@livestore/wa-sqlite': ^1.0.5
  '@radix-ui/react-label': ^2.1.7
  '@radix-ui/react-select': ^2.2.5
  '@radix-ui/react-slider': ^1.3.5
  '@radix-ui/react-slot': ^1.2.3
  '@radix-ui/react-switch': ^1.2.5
  '@tailwindcss/vite': ^4.1.11
  '@tanstack/eslint-config': ^0.3.0
  '@tanstack/react-form': ^1.15.1
  '@tanstack/react-query': ^5.83.1
  '@tanstack/react-router': ^1.130.9
  '@tanstack/react-router-devtools': ^1.130.9
  '@tanstack/router-plugin': ^1.130.9
  '@testing-library/dom': ^10.4.1
  '@testing-library/react': ^16.3.0
  '@types/node': ^24.1.0
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.7
  '@vitejs/plugin-react': ^4.7.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  eslint: ^9.32.0
  eslint-plugin-better-tailwindcss: ^3.7.3
  eslint-plugin-react: ^7.37.5
  globals: ^16.3.0
  jsdom: ^26.1.0
  lucide-react: ^0.535.0
  prettier: ^3.6.2
  react: ^19.1.1
  react-dom: ^19.1.1
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.11
  tailwindcss-animate: ^1.0.7
  typescript: ^5.8.3
  typescript-eslint: ^8.38.0
  vite: ^7.0.6
  vite-plugin-pwa: ^1.0.2
  vite-plugin-top-level-await: ^1.6.0
  vite-plugin-wasm: ^3.5.0
  vitest: ^3.2.4
  web-vitals: ^5.0.3
  workbox-window: ^7.3.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - msgpackr-extract
  - unrs-resolver
