onlyBuiltDependencies:
  - "@parcel/watcher"
  - msgpackr-extract
catalog:
  "@eslint/js": ^9.32.0
  "@journeyapps/wa-sqlite": ^1.2.6
  "@powersync/kysely-driver": ^1.2.0
  "@powersync/react": ^1.5.3
  "@powersync/tanstack-react-query": ^0.0.30
  "@powersync/web": ^1.24.0
  "@radix-ui/react-label": ^2.1.7
  "@radix-ui/react-select": ^2.2.5
  "@radix-ui/react-slider": ^1.3.5
  "@radix-ui/react-slot": ^1.2.3
  "@radix-ui/react-switch": ^1.2.5
  "@tailwindcss/vite": ^4.1.11
  "@tanstack/eslint-config": ^0.3.0
  "@tanstack/react-form": ^1.15.0
  "@tanstack/react-query": ^5.83.0
  "@tanstack/react-router": ^1.129.8
  "@tanstack/react-router-devtools": ^1.129.8
  "@tanstack/router-plugin": ^1.129.8
  "@testing-library/dom": ^10.4.0
  "@testing-library/react": ^16.3.0
  "@types/node": ^24.1.0
  "@types/react": ^19.1.8
  "@types/react-dom": ^19.1.6
  "@vitejs/plugin-react": ^4.7.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  eslint: ^9.32.0
  eslint-plugin-react: ^7.37.5
  globals: ^16.3.0
  jsdom: ^26.1.0
  lucide-react: ^0.525.0
  prettier: ^3.6.2
  react: ^19.1.0
  react-dom: ^19.1.0
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.11
  tailwindcss-animate: ^1.0.7
  typescript: ^5.8.3
  typescript-eslint: ^8.38.0
  vite: ^7.0.6
  vite-plugin-pwa: ^1.0.2
  vite-plugin-top-level-await: ^1.6.0
  vite-plugin-wasm: ^3.5.0
  vitest: ^3.2.4
  web-vitals: ^5.0.3
  zod: ^4.0.10
